name: Odata to OpenAPI Converter
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  convert:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Setup Nodejs
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      # Install npm package used to do the conversion
      - name: Install odata-openapi
        run: npm install -g odata-openapi
      # Download XML content
      - name: Download Metadata
        run: wget -S 'https://services.odata.org/V3/Northwind/Northwind.svc/$metadata' -O metadata.xml
      - run: ls -la
      # Convert the XML to OpenAPI JSON
      - name: Convert
        run: odata-openapi3 metadata.xml
      # Upload the converted file to the build output
      - uses: actions/upload-artifact@v3
        with:
          name: openapi.json
          path: metadata.openapi3.json
